### ISSUE TITLE
skeleton.sh v pimotion.sh

### ISSUE THREAD

**Issue by jsavage** [pageauc/pi-motion#2]
Hi, whilst your instructions worked well for me, I did  get stuck editing skeleton.sh.  I now realise that this step is not necessary because you distributed pimotion.sh in the tar file.
So to simplify the script further I suggest that the skeleton step be dropped and replaced with 

sudo cp pimotion.sh /etc/init.d
cd /etc/init.d
sudo update-rc.d pimotion.sh defaults  # as per my pull request

James

**Comment by onaclov2000** [comment]
As a side note to the google drive stuff, there might be the option of using dropbox? I was reading some tutorials on opencv and one individual was using that....just a thought. (I may poke at it when I have time, but it's pretty low priority, so not sure when if ever.)

**Comment by pageauc** [comment]
I have not updated pi-motion-grive but pi-timolo has a good google drive interface that I call gdrive.
https://github.com/pageauc/pi-timolo/tree/master/source
This works very well and does not require any dependencies.  You can give it a try.  Also I have seen and use drop box connections but still prefer gdrive interface to my google drive (personal preference)
Thanks for your comment
Claude ...
